### ISSUE TITLE
Customer Profile: link sometimes doesn't work

### ISSUE THREAD

**Issue by karl-denby** [Jureva/Heirloom-Era#1]
__Problem:__
Customer profile link is invalid after a user logs in.

__Steps to recreate:__
1. Log in to the website, this will bring you to your user profile
2. Click "Customer Profile"
3. Error shows invalid URL "customers/customers"

__Other information:__
Clicking any other page then "Customer Profile" will bring you to a list of all customers.

**Comment by karl-denby** [comment]
Problem also occurs in Ideas page if you click the Ideas header, appears you can't navigate to a page you are already on.

**Comment by Jureva** [comment]
Thanks, looking at it now..

**Comment by Jureva** [comment]
Problem solved.
